### ISSUE TITLE
loader.js is not merged in the vendor.js file

### ISSUE THREAD

**Issue by jbailey4** [duizendnegen/ember-cli-lazy-load#11]
When using this addon with an updated version of ember-cli >= 2.3.0-beta.2, the loader.js module is not loaded in the vendor.js file, resulting in a JS error stating that `define` is not defined. 

I believe this is due to an upstream change in ember-cli, which changed the loader.js dep to a node module in package.json. Previously loader.js was a bower component. 
See: [https://github.com/ember-cli/ember-cli/blob/v2.3.0-beta.2/CHANGELOG.md#230-beta2](https://github.com/ember-cli/ember-cli/blob/v2.3.0-beta.2/CHANGELOG.md#230-beta2)

**Comment by duizendnegen** [comment]
Thanks for the heads-up - I updated the readme that an exact `ember-cli` version of 2.2.0 is needed. I'm open for PRs to improve this, but personally, I am not pushing this project much further and rather looking at `ember-engines`.

**Comment by jbailey4** [comment]
Yeah I definitely agree moving forward with ember-engines is much better long-term. However, our team is desperate for lazy loading and need an implementation for the short term. This addon works great for that use case and doesn't require a ton of changes to the overall app structure, which is what we want for an easy transition to ember engines/lazy loading.

I have a fix for this issue locally that works with newer versions of ember-cli and would be happy to submit a PR.

**Comment by duizendnegen** [comment]
Happily accepting a PR! Especially if it supports both ember-cli versions
