### ISSUE TITLE
Lazy load css - Bundling fails when used with sass

### ISSUE THREAD

**Issue by Abuthahir-Sulaiman** [duizendnegen/ember-cli-lazy-load#15]
@duizendnegen @B-Stefan First of all, Thanks to ember-cli-lazy-load, we were able to lazy load our js and making our website more performant.  However over the years our app.css file is hugely bloated and its causing an impact in initial page loading. 

We had tried to bundle the app.scss similar to js but we are blocked due to an impediment. We are using sass for styling and the ember-cli-sass takes care of compiling the sass into css. We face an issue where when try to bundle the css, Due to import and extends being used in sass, we ended in duplicating the mixins css code in the bundles.css we generate so that we needed to resolve the dependecies.

Can you help us if u had already tried to lazy load the css along with bundling, and faced an similar impediment like code duplication for mixins using sass. Any help would be much appreciated. Thanks in advance.

**Comment by duizendnegen** [comment]
Hi @Abuthahir-Sulaiman - I would strongly recommend using https://github.com/ember-engines/ember-engines instead of ember cli lazy load.
We haven't optimized the CSS bundling in this, and aren't planning to maintain this repo anymore.
